# shellcheck shell=bash
# Part of AZHDAR (modular)

# -------------------- Mimic configs (local/remote) --------------------

mimic_local_conf_path(){
  local wan; wan="$(detect_wan_if)"
  [[ -n "$wan" ]] || return 1
  echo "/etc/mimic/${wan}.conf"
}

mimic_profile_block_local(){
  # Print Mimic filter lines for a profile on the IR host.
  local name="$1"
  local wg_port ir_local out_ip
  wg_port="$(profile_read_var "$name" WG_PORT 2>/dev/null || true)"
  ir_local="$(profile_read_var "$name" IR_LOCAL_IP 2>/dev/null || true)"
  out_ip="$(profile_read_var "$name" OUT_PUBLIC_IP 2>/dev/null || true)"
  [[ -n "$wg_port" && -n "$ir_local" && -n "$out_ip" ]] || return 1
  cat <<EOF

# Profile: ${name}
filter = local=${ir_local}:${wg_port}
filter = remote=${out_ip}:${wg_port}
EOF
}

mimic_profile_block_remote(){
  # Print Mimic filter lines for a profile on the OUT host.
  local name="$1"
  local wg_port out_local ir_ip
  wg_port="$(profile_read_var "$name" WG_PORT 2>/dev/null || true)"
  out_local="$(profile_read_var "$name" OUT_LOCAL_IP 2>/dev/null || true)"
  ir_ip="$(profile_read_var "$name" IR_PUBLIC_IP 2>/dev/null || true)"
  [[ -n "$wg_port" && -n "$out_local" && -n "$ir_ip" ]] || return 1
  cat <<EOF

# Profile: ${name}
filter = local=${out_local}:${wg_port}
filter = remote=${ir_ip}:${wg_port}
EOF
}

mimic_should_include_profile(){
  # Include if enabled OR is the currently active profile (during install/repair).
  local name="$1"
  local enabled
  enabled="$(profile_read_var "$name" PROFILE_ENABLED 2>/dev/null || echo 0)"
  [[ "$enabled" == "1" ]] && return 0
  [[ -n "${PROFILE:-}" && "$name" == "$PROFILE" ]] && return 0
  return 1
}

mimic_should_include_profile_for_remote(){
  # Include only profiles that target the same remote host, plus current.
  local name="$1"
  local host
  host="$(profile_read_var "$name" OUT_SSH_HOST 2>/dev/null || true)"
  [[ -n "${OUT_SSH_HOST:-}" && "$host" == "${OUT_SSH_HOST}" ]] || return 1
  mimic_should_include_profile "$name"
}

mimic_rebuild_local_excluding(){
  # Rebuild local Mimic config for all enabled profiles, excluding the given name.
  local exclude="${1:-}"
  local wan; wan="$(detect_wan_if)"
  [[ -n "$wan" ]] || return 0
  mkdir -p /etc/mimic

  local cfg="/etc/mimic/${wan}.conf"
  local tmp; tmp="$(mktemp -t azhdar-mimic.local.XXXXXX.conf)"

  cat >"$tmp" <<EOF
# Generated by AZHDAR v${SCRIPT_VERSION} - Mimic config (IR)
log.verbosity = info
handshake = 2:3
keepalive = 180:10:3:600
EOF

  local n any=0
  while read -r n; do
    n="$(safe_name "$n")"; [[ -n "$n" ]] || continue
    [[ -n "$exclude" && "$n" == "$exclude" ]] && continue
    local enabled
    enabled="$(profile_read_var "$n" PROFILE_ENABLED 2>/dev/null || echo 0)"
    [[ "$enabled" == "1" ]] || continue
    if mimic_profile_block_local "$n" >>"$tmp" 2>/dev/null; then
      any=1
    fi
  done < <(profiles_list)

  if (( any == 0 )); then
    # No active filters left -> stop mimic and remove config.
    command -v systemctl >/dev/null 2>&1 && systemctl stop "mimic@${wan}" >/dev/null 2>&1 || true
    rm -f "$cfg" 2>/dev/null || true
    rm -f "$tmp" 2>/dev/null || true
    return 0
  fi

  mv -f "$tmp" "$cfg"
  chmod 644 "$cfg" 2>/dev/null || true
  command -v systemctl >/dev/null 2>&1 && systemctl restart "mimic@${wan}" >/dev/null 2>&1 || true
  return 0
}

mimic_rebuild_remote_excluding(){
  # Rebuild remote Mimic config for all enabled profiles pointing to this OUT host, excluding the given name.
  local exclude="${1:-}"
  [[ -n "${OUT_SSH_HOST:-}" ]] || return 0
  [[ -n "${REMOTE_WAN_IF:-}" ]] || REMOTE_WAN_IF="$(remote_detect_wan_if_quiet || true)"
  [[ -n "${REMOTE_WAN_IF:-}" ]] || return 0

  local blocks=""
  local n
  while read -r n; do
    n="$(safe_name "$n")"; [[ -n "$n" ]] || continue
    [[ -n "$exclude" && "$n" == "$exclude" ]] && continue
    local host enabled
    host="$(profile_read_var "$n" OUT_SSH_HOST 2>/dev/null || true)"
    enabled="$(profile_read_var "$n" PROFILE_ENABLED 2>/dev/null || echo 0)"
    [[ "$host" == "${OUT_SSH_HOST}" ]] || continue
    [[ "$enabled" == "1" ]] || continue
    blocks+="$(mimic_profile_block_remote "$n" 2>/dev/null || true)"
  done < <(profiles_list)

  if [[ -z "$blocks" ]]; then
    ssh_run_root_best_effort "systemctl stop mimic@${REMOTE_WAN_IF} >/dev/null 2>&1 || true; rm -f /etc/mimic/${REMOTE_WAN_IF}.conf >/dev/null 2>&1 || true" >/dev/null 2>&1 || true
    return 0
  fi

  local blocks_b64
  blocks_b64="$(printf '%s' "$blocks" | base64 -w0 2>/dev/null || printf '%s' "$blocks" | base64 2>/dev/null | tr -d '\n')"

  ssh_run_stdin_env_root_best_effort "SCRIPT_VERSION=${SCRIPT_VERSION}" "REMOTE_WAN_IF=${REMOTE_WAN_IF}" "MIMIC_BLOCKS_B64=${blocks_b64}" <<'REMOTE' >/dev/null 2>&1 || true
set -euo pipefail
WAN_IF="${REMOTE_WAN_IF}"
mkdir -p /etc/mimic

MIMIC_BLOCKS="$(printf '%s' "${MIMIC_BLOCKS_B64:-}" | base64 -d 2>/dev/null || true)"

cat >"/etc/mimic/${WAN_IF}.conf" <<EOF
# Generated by AZHDAR v${SCRIPT_VERSION} - Mimic config (OUT)
log.verbosity = info
handshake = 0:0
${MIMIC_BLOCKS}
EOF

chmod 644 "/etc/mimic/${WAN_IF}.conf" 2>/dev/null || true
systemctl restart "mimic@${WAN_IF}" >/dev/null 2>&1 || true
REMOTE
  return 0
}

mimic_profile_present_local(){
  local name="$1"
  local wan; wan="$(detect_wan_if)"
  [[ -n "$wan" ]] || return 1
  local cfg="/etc/mimic/${wan}.conf"
  [[ -f "$cfg" ]] || return 1
  grep -Fq "# Profile: ${name}" "$cfg" 2>/dev/null
}

mimic_profile_present_remote(){
  local name="$1"
  [[ -n "${REMOTE_WAN_IF:-}" ]] || REMOTE_WAN_IF="$(remote_detect_wan_if_quiet || true)"
  [[ -n "${REMOTE_WAN_IF:-}" ]] || return 1
  ssh_run "grep -Fq '# Profile: ${name}' /etc/mimic/${REMOTE_WAN_IF}.conf 2>/dev/null" >/dev/null 2>&1
}

write_mimic_conf_local(){
  step "Write Mimic config (local)"
  local wan; wan="$(detect_wan_if)"
  [[ -n "$wan" ]] || die "Cannot detect WAN interface."
  mkdir -p /etc/mimic

  local cfg="/etc/mimic/${wan}.conf"
  local tmp; tmp="$(mktemp -t azhdar-mimic.local.XXXXXX.conf)"

  cat >"$tmp" <<EOF
# Generated by AZHDAR v${SCRIPT_VERSION} - Mimic config (IR)
log.verbosity = info
handshake = 2:3
keepalive = 180:10:3:600
EOF

  local n any=0
  while read -r n; do
    n="$(safe_name "$n")"; [[ -n "$n" ]] || continue
    mimic_should_include_profile "$n" || continue
    if mimic_profile_block_local "$n" >>"$tmp" 2>/dev/null; then
      any=1
    fi
  done < <(profiles_list)

  if (( any == 0 )); then
    warn "No enabled profiles found for Mimic(local). Leaving config with base settings only."
  fi

  mv -f "$tmp" "$cfg"
  chmod 644 "$cfg" 2>/dev/null || true
  ok "Local Mimic config written: ${cfg}"
}

write_mimic_conf_remote(){
  step "Write Mimic config (remote)"
  # Build one config per remote host; include all profiles that target this OUT host.
  local blocks=""
  local n
  while read -r n; do
    n="$(safe_name "$n")"; [[ -n "$n" ]] || continue
    mimic_should_include_profile_for_remote "$n" || continue
    blocks+="$(mimic_profile_block_remote "$n" 2>/dev/null || true)"
  done < <(profiles_list)

  # Transport blocks safely (newlines) via base64.
  local blocks_b64=""
  if have_cmd base64; then
    blocks_b64="$(printf '%s' "$blocks" | base64 -w0 2>/dev/null || printf '%s' "$blocks" | base64 2>/dev/null | tr -d '\n')"
  else
    die "base64 is required for remote Mimic config generation."
  fi

  local out
  out="$(ssh_run_stdin_env_root \
    "SCRIPT_VERSION=${SCRIPT_VERSION}" \
    "MIMIC_BLOCKS_B64=${blocks_b64}" <<'REMOTE'
set -euo pipefail

detect_if() {
  local ifc=""
  ifc="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}' || true)"
  [[ -n "${ifc}" ]] || ifc="$(ip -4 route show default 2>/dev/null | awk 'NR==1{print $5; exit}' || true)"
  [[ -n "${ifc}" ]] || ifc="$(ip -br link 2>/dev/null | awk '$1!="lo" && $2 ~ /UP/ {print $1; exit}' || true)"
  echo "${ifc}"
}

WAN_IF="$(detect_if)"
[[ -n "${WAN_IF}" ]] || { echo "ERR:NO_IF"; exit 7; }

mkdir -p /etc/mimic

MIMIC_BLOCKS=""
if command -v base64 >/dev/null 2>&1; then
  MIMIC_BLOCKS="$(printf '%s' "${MIMIC_BLOCKS_B64:-}" | base64 -d 2>/dev/null || true)"
fi

cat >"/etc/mimic/${WAN_IF}.conf" <<EOF
# Generated by AZHDAR v${SCRIPT_VERSION} - Mimic config (OUT)
log.verbosity = info
handshake = 0:0
${MIMIC_BLOCKS}
EOF

chmod 644 "/etc/mimic/${WAN_IF}.conf"
echo "WAN_IF=${WAN_IF}"
REMOTE
)" || true

  if echo "$out" | grep -q "ERR:NO_IF"; then
    die "Remote WAN interface detection failed."
  fi
  REMOTE_WAN_IF="$(echo "$out" | sed -n 's/^WAN_IF=//p' | tail -n1 | tr -d '\r')"
  [[ -n "${REMOTE_WAN_IF:-}" ]] || die "Remote Mimic interface name not detected."
  ok "Remote Mimic config written: /etc/mimic/${REMOTE_WAN_IF}.conf"
}

enable_mimic_local(){
  local wan; wan="$(detect_wan_if)"
  [[ -n "$wan" ]] || return 0
  systemctl daemon-reload >/dev/null 2>&1 || true
  systemctl enable --now "mimic@${wan}" >/dev/null 2>&1 || true
}

enable_mimic_remote(){
  local rif="${REMOTE_WAN_IF:-}"
  if [[ -z "$rif" ]]; then
    rif="$(remote_detect_wan_if_quiet || true)"
    if [[ -n "$rif" ]]; then
      REMOTE_WAN_IF="$rif"
      profile_save >/dev/null 2>&1 || true
    fi
  fi
  [[ -n "$rif" ]] || return 0
  ssh_run_root_best_effort "systemctl daemon-reload >/dev/null 2>&1 || true; systemctl enable --now mimic@${rif} >/dev/null 2>&1 || true" >/dev/null 2>&1 || true
}

