# shellcheck shell=bash
# Part of AZHDAR (modular)

# -------------------- Offline (no SSH) remote bundle --------------------
# هدف: بدون نیاز به SSH، سمت ریموت (OUT) را با یک فایل self-extract و یک خط اجرا نصب کنیم.

_gen_keypair(){
  # prints: priv\npub
  local priv pub
  priv="$(wg genkey 2>/dev/null | tr -d '\r\n' || true)"
  [[ -n "$priv" ]] || return 1
  pub="$(printf '%s' "$priv" | wg pubkey 2>/dev/null | tr -d '\r\n' || true)"
  [[ -n "$pub" ]] || return 1
  printf '%s\n%s\n' "$priv" "$pub"
}

_build_remote_mimic_blocks(){
  local blocks="" n
  while read -r n; do
    n="$(safe_name "$n")"; [[ -n "$n" ]] || continue
    mimic_should_include_profile_for_remote "$n" || continue
    blocks+="$(mimic_profile_block_remote "$n" 2>/dev/null || true)"
  done < <(profiles_list)
  printf '%s' "$blocks"
}

_build_remote_wg_conf(){
  # uses: OUT_PRIVKEY IR_PUBKEY, addr/allowed
  local addr="" allowed=""

  if [[ "${ENABLE_TUN_IPV4:-1}" == "1" && -n "${OUT_WG_IP:-}" && -n "${TUN_SUBNET:-}" ]]; then
    local prefix4="${TUN_SUBNET##*/}"
    addr="${OUT_WG_IP}/${prefix4}"
    allowed="${IR_WG_IP}/32"
  fi

  if [[ "${ENABLE_TUN_IPV6:-0}" == "1" && -n "${TUN_SUBNET6:-}" && -n "${OUT_WG_IP6:-}" && -n "${IR_WG_IP6:-}" ]]; then
    local prefix6="${TUN_SUBNET6##*/}"
    [[ -n "$addr" ]] && addr+=", "
    addr+="${OUT_WG_IP6}/${prefix6}"
    [[ -n "$allowed" ]] && allowed+=", "
    allowed+="${IR_WG_IP6}/128"
  fi

  [[ -n "$addr" && -n "$allowed" ]] || die "No tunnel address families enabled. Enable IPv4 and/or IPv6."

  cat <<CFG
# Generated by AZHDAR v${SCRIPT_VERSION} - WireGuard (OUT) offline bundle
[Interface]
PrivateKey = ${OUT_PRIVKEY}
Address = ${addr}
ListenPort = ${WG_PORT}
MTU = ${MTU}

[Peer]
PublicKey = ${IR_PUBKEY}
CFG

  if [[ "${USE_PSK}" == "1" && -n "${PSK_VALUE:-}" ]]; then
    echo "PresharedKey = ${PSK_VALUE}"
  fi

  cat <<CFG
AllowedIPs = ${allowed}
CFG
}

_build_remote_installer(){
  # args: outdir
  local outdir="$1"
  mkdir -p "$outdir"
  local wg_conf
  wg_conf="$(_build_remote_wg_conf)"

  # Write installer script with placeholders, then fill safely.
    cat >"${outdir}/run-remote.sh" <<'SH'
#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

need_root(){
  if [[ "${EUID}" -ne 0 ]]; then
    echo "This installer must run as root. Try: sudo bash $0" >&2
    exit 1
  fi
}

detect_if(){
  local ifc=""
  ifc="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="dev"){print $(i+1); exit}}' || true)"
  [[ -n "${ifc}" ]] || ifc="$(ip -4 route show default 2>/dev/null | awk 'NR==1{print $5; exit}' || true)"
  [[ -n "${ifc}" ]] || ifc="$(ip -br link 2>/dev/null | awk '$1!="lo" && $2 ~ /UP/ {print $1; exit}' || true)"
  echo "${ifc}"
}

pkg_mgr(){
  command -v apt-get >/dev/null 2>&1 && { echo apt; return; }
  command -v dnf >/dev/null 2>&1 && { echo dnf; return; }
  command -v yum >/dev/null 2>&1 && { echo yum; return; }
  command -v pacman >/dev/null 2>&1 && { echo pacman; return; }
  echo unknown
}

os_codename(){
  local codename=""
  if [[ -r /etc/os-release ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release 2>/dev/null || true
    codename="${VERSION_CODENAME:-${UBUNTU_CODENAME:-}}"
    if [[ -z "${codename}" && -n "${VERSION:-}" ]]; then
      local tmp
      tmp="${VERSION#*(}"; tmp="${tmp%%)*}"
      if [[ -n "${tmp}" && "${tmp}" != "${VERSION}" ]]; then
        codename="${tmp%% *}"
      fi
    fi
  fi
  if [[ -z "${codename}" ]] && command -v lsb_release >/dev/null 2>&1; then
    codename="$(lsb_release -cs 2>/dev/null || true)"
  fi
  echo "${codename,,}"
}

apt_install_retry(){
  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y "$@" >/dev/null 2>&1 && return 0
  apt-get -f install -y >/dev/null 2>&1 || true
  apt-get install -y "$@" >/dev/null 2>&1
}

install_deps(){
  local pm; pm="$(pkg_mgr)"
  case "$pm" in
    apt)
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -y >/dev/null 2>&1 || true

      # IMPORTANT: Mimic-DKMS requires these.
      if ! apt-get install -y dkms build-essential "linux-headers-$(uname -r)" >/dev/null 2>&1; then
        apt-get -f install -y >/dev/null 2>&1 || true
        apt-get install -y dkms build-essential "linux-headers-$(uname -r)" >/dev/null 2>&1 ||           apt-get install -y dkms build-essential linux-headers-generic >/dev/null 2>&1 || true
      fi

      # Core networking tools
      apt_install_retry wireguard-tools wireguard iptables iproute2 iputils-ping curl ca-certificates git netcat-openbsd tcpdump python3 xz-utils lz4 >/dev/null 2>&1 || true
      ;;
    dnf)
      dnf install -y wireguard-tools iptables iproute iputils curl ca-certificates git make gcc dkms nmap-ncat tcpdump python3 xz lz4 >/dev/null 2>&1 || true
      ;;
    yum)
      yum install -y wireguard-tools iptables iproute iputils curl ca-certificates git make gcc dkms nmap-ncat tcpdump python3 xz lz4 >/dev/null 2>&1 || true
      ;;
    pacman)
      pacman -Sy --noconfirm wireguard-tools iptables iproute2 iputils curl ca-certificates git base-devel dkms netcat tcpdump python xz lz4 >/dev/null 2>&1 || true
      ;;
    *)
      echo "Unsupported package manager. Please install: wireguard-tools, iptables, iproute2, curl, ca-certificates, dkms" >&2
      ;;
  esac
  modprobe wireguard >/dev/null 2>&1 || true
}

install_mimic_apt_only(){
  # Mimic installer (Debian/Ubuntu). On other distros we skip (best-effort).
  if command -v mimic >/dev/null 2>&1; then
    return 0
  fi
  if ! command -v apt-get >/dev/null 2>&1; then
    echo "[!] mimic not installed (no apt). Skipping mimic install." >&2
    return 0
  fi

  local codename; codename="$(os_codename)"
  if [[ -z "${codename}" ]]; then
    echo "[!] Cannot detect OS codename; skipping mimic install." >&2
    return 0
  fi

  local json urls deb1 deb2 tmp
  tmp="/tmp/mimic-install.$$"
  rm -rf "$tmp"; mkdir -p "$tmp"

  json="$(curl -fsSL --max-time 10 https://api.github.com/repos/hack3ric/mimic/releases/latest 2>/dev/null || true)"
  urls="$(printf "%s" "$json" | sed -n 's/.*"browser_download_url"[ ]*:[ ]*"\([^"]*\)".*//p' || true)"

  deb1="$(printf "%s
" "$urls" | grep -E "/${codename}_mimic_[^/]*_amd64\.deb$" | head -n1 || true)"
  deb2="$(printf "%s
" "$urls" | grep -E "/${codename}_mimic-dkms_[^/]*_amd64\.deb$" | head -n1 || true)"

  # Mirror fallback (useful when GitHub is blocked). You can override:
  #   export AZHDAR_MIRROR_BASE="https://api.github.com/repos/m0000hamad/AZHDAR/contents/assets"
  local MIRROR_BASE="${AZHDAR_MIRROR_BASE:-${ASSET_MIRROR_BASE:-https://api.github.com/repos/m0000hamad/AZHDAR/contents/assets}}"
  if [[ -z "$deb1" || -z "$deb2" ]]; then
    deb1="${MIRROR_BASE}/${codename}_mimic_0.7.0-1_amd64.deb"
    deb2="${MIRROR_BASE}/${codename}_mimic-dkms_0.7.0-1_amd64.deb"
  fi

  azhdar_gh_hdr_args "$deb1" 2>/dev/null || AZ_GH_HDR=()
  curl -fL --connect-timeout 6 --max-time 120 ${AZ_GH_HDR[@]+"${AZ_GH_HDR[@]}"} "$deb1" -o "$tmp/mimic.deb" >/dev/null 2>&1 || true
  azhdar_gh_hdr_args "$deb2" 2>/dev/null || AZ_GH_HDR=()
  curl -fL --connect-timeout 6 --max-time 120 ${AZ_GH_HDR[@]+"${AZ_GH_HDR[@]}"} "$deb2" -o "$tmp/mimic-dkms.deb" >/dev/null 2>&1 || true

  if [[ -s "$tmp/mimic.deb" && -s "$tmp/mimic-dkms.deb" ]]; then
    dpkg-deb -I "$tmp/mimic.deb" >/dev/null 2>&1 || return 0
    dpkg-deb -I "$tmp/mimic-dkms.deb" >/dev/null 2>&1 || return 0

    if ! apt-get install -y "$tmp/mimic.deb" "$tmp/mimic-dkms.deb" >/dev/null 2>&1; then
      apt-get -f install -y >/dev/null 2>&1 || true
      apt-get install -y "$tmp/mimic.deb" "$tmp/mimic-dkms.deb" >/dev/null 2>&1 || true
    fi
  fi
}

detect_src_ip(){
  # args: dst_ip
  local dst="$1" src=""
  src="$(ip -4 route get "$dst" 2>/dev/null | awk '/src/ {for(i=1;i<=NF;i++){if($i=="src"){print $(i+1); exit}}}' || true)"
  echo "$src"
}

open_ports_and_rst_drop(){
  local port="__WG_PORT__"
  # Allow BOTH TCP+UDP on the public port (WG is UDP, Mimic makes it look TCP)
  local proto
  for proto in tcp udp; do
    iptables -C INPUT -p "$proto" --dport "$port" -j ACCEPT >/dev/null 2>&1 || iptables -I INPUT -p "$proto" --dport "$port" -j ACCEPT >/dev/null 2>&1 || true
  done
  if command -v ufw >/dev/null 2>&1; then
    ufw allow "${port}/tcp" >/dev/null 2>&1 || true
    ufw allow "${port}/udp" >/dev/null 2>&1 || true
  fi
  # Prevent kernel from sending RST on Mimic fake TCP flow
  iptables -t raw -C OUTPUT -p tcp --sport "$port" --tcp-flags RST RST -j DROP >/dev/null 2>&1 ||     iptables -t raw -I OUTPUT -p tcp --sport "$port" --tcp-flags RST RST -j DROP >/dev/null 2>&1 || true
}

apply_files(){
  local wan_if="$1"

  mkdir -p /etc/wireguard /etc/mimic

  # WireGuard key + conf
  cat >"/etc/wireguard/__WG_IF__.key" <<'K'
__OUT_PRIVKEY__
K
  chmod 600 "/etc/wireguard/__WG_IF__.key" || true

  cat >"/etc/wireguard/__WG_IF__.conf" <<'WG'
__WG_CONF__
WG
  chmod 600 "/etc/wireguard/__WG_IF__.conf" || true

  # Mimic conf (OUT) - compute local src IP automatically
  local src_ip
  src_ip="$(detect_src_ip "__IR_PUBLIC_IP__")"
  if [[ -z "$src_ip" ]]; then
    # fallback: first IPv4 on wan_if
    src_ip="$(ip -4 addr show dev "$wan_if" 2>/dev/null | awk '/inet /{print $2}' | head -n1 | cut -d/ -f1 || true)"
  fi

  cat >"/etc/mimic/${wan_if}.conf" <<EOF
# Generated by AZHDAR v__SCRIPT_VERSION__ - Mimic config (OUT)
log.verbosity = info
handshake = 0:0

# Profile: __PROFILE__
filter = local=${src_ip}:__WG_PORT__
filter = remote=__IR_PUBLIC_IP__:__WG_PORT__
EOF
  chmod 644 "/etc/mimic/${wan_if}.conf" || true
}

enable_services(){
  local wan_if="$1"
  systemctl daemon-reload >/dev/null 2>&1 || true
  systemctl enable --now "wg-quick@__WG_IF__" >/dev/null 2>&1 || true
  systemctl enable --now "mimic@${wan_if}" >/dev/null 2>&1 || true
}

parse_peer_ips(){
  # Best-effort: parse AllowedIPs from WireGuard conf (first peer).
  local conf="/etc/wireguard/__WG_IF__.conf"
  [[ -r "$conf" ]] || return 0
  sed -n 's/^AllowedIPs[[:space:]]*=[[:space:]]*//p' "$conf" | head -n1 | \
    tr ',' '\n' | awk '{print $1}' | cut -d/ -f1 | sed '/^$/d'
}

wg_handshake_recent(){
  local ifc="__WG_IF__" hs now
  command -v wg >/dev/null 2>&1 || return 1
  hs="$(wg show "$ifc" latest-handshakes 2>/dev/null | awk 'NR==1{print $2}' || echo 0)"
  [[ "$hs" =~ ^[0-9]+$ ]] || return 1
  (( hs > 0 )) || return 1
  now="$(date +%s 2>/dev/null || echo 0)"
  (( now - hs <= 180 ))
}

wg_ping_peer_once(){
  # args: ip
  local ifc="__WG_IF__" ip="$1"
  [[ -n "$ip" ]] || return 1
  if [[ "$ip" == *:* ]]; then
    ping -6 -c 1 -W 1 -I "$ifc" "$ip" >/dev/null 2>&1
  else
    ping -4 -c 1 -W 1 -I "$ifc" "$ip" >/dev/null 2>&1
  fi
}

final_link_check(){
  # Goal: at the end on OUT, print OK if OUT<->IR link is established.
  local ok=0 try ip

  # Wait a bit for handshake (IR keepalive will usually trigger this).
  for try in $(seq 1 15); do
    wg_handshake_recent && { ok=1; break; }
    sleep 2
  done

  # If no recent handshake yet, attempt ping to peer WG IP(s) (best-effort).
  if (( ok == 0 )); then
    while read -r ip; do
      wg_ping_peer_once "$ip" && { ok=1; break; }
    done < <(parse_peer_ips || true)
  fi

  if (( ok == 1 )); then
    echo "OK"
    return 0
  fi

  echo "NOT OK"
  echo "Debug: wg show __WG_IF__" >&2
  return 1
}

main(){
  need_root

  local wan_if
  wan_if="$(detect_if)"
  if [[ -z "${wan_if}" ]]; then
    echo "Cannot detect WAN interface." >&2
    exit 7
  fi

  echo "[*] WAN interface: ${wan_if}"
  echo "[*] Installing deps (best-effort)..."
  install_deps

  echo "[*] Installing mimic (best-effort, apt only)..."
  install_mimic_apt_only

  echo "[*] Opening ports + applying RST-drop (best-effort)..."
  open_ports_and_rst_drop || true

  echo "[*] Writing configs..."
  apply_files "$wan_if"

  echo "[*] Enabling services..."
  enable_services "$wan_if"

  echo "[+] Done. Check on OUT:" 
  echo "    systemctl status wg-quick@__WG_IF__ --no-pager"
  echo "    systemctl status mimic@${wan_if} --no-pager"
  echo "    wg show __WG_IF__"

  echo "[*] Link check (OUT -> IR):"
  final_link_check || true
}

main "$@"
SH

  python3 - <<PY
import pathlib
p = pathlib.Path("${outdir}/run-remote.sh")
text = p.read_text()
text = text.replace("__WG_IF__", "${WG_IF}")
text = text.replace("__SCRIPT_VERSION__", "${SCRIPT_VERSION}")
text = text.replace("__OUT_PRIVKEY__", "${OUT_PRIVKEY}")
text = text.replace("__WG_CONF__", r"""${wg_conf}""")
text = text.replace("__PROFILE__", "${PROFILE}")
text = text.replace("__IR_PUBLIC_IP__", "${IR_PUBLIC_IP}")
text = text.replace("__WG_PORT__", "${WG_PORT}")
p.write_text(text)
PY

  chmod +x "${outdir}/run-remote.sh" || true
}

_make_self_extract(){
  # args: sourcedir outfile
  local src="$1" out="$2"
  local tgz="${out}.tar.gz"
  tar -C "$(dirname "$src")" -czf "$tgz" "$(basename "$src")"

  local b64
  b64="$(base64 -w0 "$tgz" 2>/dev/null || base64 "$tgz" 2>/dev/null | tr -d '\n')"

  cat >"$out" <<'EOSEL'
#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

_payload_b64='__PAYLOAD_B64__'
_tmp="/tmp/azhdar-offline-$$"
mkdir -p "$_tmp"

cleanup(){ rm -rf "$_tmp" >/dev/null 2>&1 || true; }
trap cleanup EXIT

printf '%s' "$_payload_b64" | base64 -d >"$_tmp/bundle.tgz"

tar -C "$_tmp" -xzf "$_tmp/bundle.tgz"

cd "$_tmp/__DIR__"
exec bash ./run-remote.sh
EOSEL

  python3 - <<PY
import pathlib
p = pathlib.Path("$out")
text = p.read_text()
text = text.replace("__PAYLOAD_B64__", "${b64}")
text = text.replace("__DIR__", "$(basename "$src")")
p.write_text(text)
PY

  chmod +x "$out" || true
  rm -f "$tgz" >/dev/null 2>&1 || true
}

advanced_tunnel_ip_wizard(){
  # Offline-friendly tunnel IP allocator (no SSH required).
  echo
  echo -e "${DIM}Tunnel IP allocation:${RST}"
  echo " 1) Auto (pick subnet + WG IPs)"
  echo " 2) Manual (set subnet + WG IPs)"
  local _def="1" _ia=""
  [[ "${TUN_IP_ASSIGN:-auto}" == "manual" ]] && _def="2" || true
  while true; do
    read -rp "Select [${_def}]: " _ia || true
    _ia="${_ia:-${_def}}"
    case "${_ia}" in
      1) TUN_IP_ASSIGN="auto"; break ;;
      2) TUN_IP_ASSIGN="manual"; break ;;
      *) warn "Invalid choice." ;;
    esac
  done

  if [[ "${TUN_IP_ASSIGN}" == "manual" ]]; then
    # Provided by lib/advanced_tunnel_ip.sh (loaded by azhdar)
    tunnel_manual_set || true
  else
    if [[ "${ENABLE_TUN_IPV4:-1}" == "1" ]]; then
      pick_subnet_pairwise || true
    fi
    if [[ "${ENABLE_TUN_IPV6:-0}" == "1" ]]; then
      pick_subnet6_pairwise || true
    fi
  fi
}
offline_bundle_wizard(){
  banner
  echo -e "${BOLD}${WHT}Offline install (no SSH) - build remote one-liner bundle${RST}"
  hr
  [[ -n "${PROFILE:-}" ]] || die "No active profile. Create/select one first."

  install_deps_local

  # Local IR public IP suggestion
  local myip=""
  myip="$(public_ipv4 2>/dev/null || true)"
  [[ -n "$myip" ]] && IR_PUBLIC_IP="${IR_PUBLIC_IP:-$myip}"
  IR_PUBLIC_IP="$(prompt_ipv4 "IR public IP (this server)" "${IR_PUBLIC_IP:-}")"

  OUT_PUBLIC_IP="$(prompt_host "OUT public IP/host (no SSH)" "${OUT_PUBLIC_IP:-}")"

  # Mimic filter IP on IR: src IP used to reach OUT
  if [[ -z "${IR_LOCAL_IP:-}" && -n "${OUT_PUBLIC_IP:-}" ]]; then
    IR_LOCAL_IP="$(detect_src_ip "${OUT_PUBLIC_IP}" 2>/dev/null | tr -d '\n\r' || true)"
  fi
  if [[ -z "${IR_LOCAL_IP:-}" ]]; then
    IR_LOCAL_IP="$(prompt_ipv4 'IR local/source IP used to reach OUT (Mimic filter)' '')"
  else
    info "IR local IP (auto): ${IR_LOCAL_IP}"
  fi

  # Port selection: only local checks + profile conflicts
  local suggested
  suggested="$(suggest_wg_port || true)"
  [[ -n "$suggested" ]] && WG_PORT="$suggested"
  while true; do
    WG_PORT="$(prompt_port "Tunnel public port (looks like TCP)" "${WG_PORT:-443}")"

    if ! ports_validate_current_or_warn; then
      local _sug
      _sug="$(ports_suggest_free_near tcp "${WG_PORT}" || true)"
      if [[ -n "${_sug:-}" && "${_sug}" != "${WG_PORT}" ]]; then
        warn "Suggested free port near ${WG_PORT}: ${_sug}"
        if [[ "$(prompt_yesno "Use suggested port ${_sug}?" "Y")" == "Y" ]]; then
          WG_PORT="${_sug}"
          continue
        fi
      fi
      warn "Selected tunnel/forward port conflicts with another profile. Check the warning above and choose a different port."
      continue
    fi

    local_port_in_use "${WG_PORT}" && warn "Selected WG_PORT=${WG_PORT} is in use on IR (this server)." || true
    break
  done

  # Optional forwarding (IR)
  echo
  echo -e "${BOLD}${WHT}Optional reverse-forward${RST}"
  hr
  echo -e "${DIM}This can forward public IR ports to OUT over the WG tunnel.${RST}"
  if [[ "$(prompt_yesno "Enable reverse-forward rules on IR?" "Y")" == "Y" ]]; then
    while true; do
      read -rp "Public TCP port(s) on IR to forward (comma-separated, empty=none) [${FORWARD_TCP_PORTS}]: " FORWARD_TCP_PORTS || true
      FORWARD_TCP_PORTS="${FORWARD_TCP_PORTS:-}"
      protect_ir_ssh_port || true
      read -rp "Public UDP port(s) on IR to forward (comma-separated, empty=none) [${FORWARD_UDP_PORTS}]: " FORWARD_UDP_PORTS || true
      FORWARD_UDP_PORTS="${FORWARD_UDP_PORTS:-}"
      VLESS_DST_PORT="$(prompt_port "Destination port on OUT (service bind port)" "${VLESS_DST_PORT:-2086}")"

      ports_validate_current_or_warn && break
      warn "One of the forward ports conflicts with another profile. Please re-enter only the forwarding ports, or leave them empty to disable forwarding."
    done
  else
    FORWARD_TCP_PORTS=""
    FORWARD_UDP_PORTS=""
  fi

  # Tunnel parameters (simplified)
  echo
  echo -e "${BOLD}${WHT}Tunnel parameters${RST}"
  hr
  echo -e "${DIM}MTU mode:${RST}"
  echo " 1) Auto (discover best common MTU)"
  echo " 2) Manual"
  local _mtu_mode_def="1" _mtu_mode=""
  [[ "${MTU_MODE:-manual}" == "manual" ]] && _mtu_mode_def="2" || true
  while true; do
    read -rp "Select [${_mtu_mode_def}]: " _mtu_mode || true
    _mtu_mode="${_mtu_mode:-${_mtu_mode_def}}"
    case "${_mtu_mode}" in
      1) MTU_MODE="auto"; break ;;
      2) MTU_MODE="manual"; break ;;
      *) warn "Invalid choice." ;;
    esac
  done
  if [[ "${MTU_MODE}" == "manual" ]]; then
    MTU="$(prompt_mtu "MTU" "${MTU:-1272}")"
  else
    MTU="${MTU:-1272}"
  fi
  KEEPALIVE="$(prompt_keepalive "PersistentKeepalive" "${KEEPALIVE:-25}")"

  echo -e "${DIM}Tunnel IP mode:${RST}"
  echo " 1) IPv4 only"
  echo " 2) IPv6 only"
  echo " 3) IPv4 + IPv6 (dual stack)"
  local _def_mode="1" _mode=""
  if [[ "${ENABLE_TUN_IPV4:-1}" == "1" && "${ENABLE_TUN_IPV6:-0}" != "1" ]]; then _def_mode="1"; fi
  if [[ "${ENABLE_TUN_IPV4:-1}" != "1" && "${ENABLE_TUN_IPV6:-0}" == "1" ]]; then _def_mode="2"; fi
  if [[ "${ENABLE_TUN_IPV4:-1}" == "1" && "${ENABLE_TUN_IPV6:-0}" == "1" ]]; then _def_mode="3"; fi
  while true; do
    read -rp "Select [${_def_mode}]: " _mode || true
    _mode="${_mode:-${_def_mode}}"
    case "${_mode}" in
      1) ENABLE_TUN_IPV4="1"; ENABLE_TUN_IPV6="0"; break ;;
      2) ENABLE_TUN_IPV4="0"; ENABLE_TUN_IPV6="1"; break ;;
      3) ENABLE_TUN_IPV4="1"; ENABLE_TUN_IPV6="1"; break ;;
      *) warn "Invalid." ;;
    esac
  done

  # Tunnel IP assignment (advanced helper)
  advanced_tunnel_ip_wizard || true

  echo
  echo -e "${BOLD}${WHT}WireGuard PSK${RST}"
  hr
  if [[ "$(prompt_yesno "Use PSK for WireGuard?" "Y")" == "Y" ]]; then
    USE_PSK="1"
  else
    USE_PSK="0"
  fi
  ensure_psk

  # Local key
  ensure_privkey_local
  IR_PUBKEY="$(get_pubkey_local | tr -d '\r' | tail -n1 || true)"
  [[ -n "${IR_PUBKEY:-}" ]] || die "Local WireGuard public key missing."

  # Remote keypair (generated locally)
  local kp priv pub
  kp="$(_gen_keypair)" || die "Failed to generate OUT WireGuard keypair."
  priv="$(printf '%s' "$kp" | sed -n '1p')"
  pub="$(printf '%s' "$kp" | sed -n '2p')"
  OUT_PRIVKEY="$priv"
  OUT_PUBKEY="$pub"

  info "IR pubkey : ${IR_PUBKEY}"
  info "OUT pubkey: ${OUT_PUBKEY} (generated locally for offline bundle)"

  # Save profile now (so keys remain cached)
  profile_save >/dev/null 2>&1 || true

  # Install mimic locally + write configs locally
  install_mimic_local
  write_mimic_conf_local

  # Write local WG config
  write_wg_conf_local

  # Apply forwarding locally (optional)
  azhdar_firewall_safety_local || true
  remove_forwarding_local || true
  setup_forward_ir || true
  persist_iptables_local || true

  # Start local services
  # Ensure local firewall allows WG_PORT (both TCP+UDP) + drop RST for fake TCP
  allow_mimic_port_local || true
  setup_rst_drop_local || true

  start_services_local || true

  # Build remote bundle
  step "Build remote offline bundle"
  local tmpdir bundle_dir outbase
  tmpdir="/tmp/azhdar-offline-bundle.${PROFILE}.$$"
  rm -rf "$tmpdir" >/dev/null 2>&1 || true
  mkdir -p "$tmpdir"

  bundle_dir="${tmpdir}/azhdar-remote-${PROFILE}"
  _build_remote_installer "$bundle_dir"

  outbase="${AZHDAR_HOME}/azhdar-remote-${PROFILE}-${SCRIPT_VERSION}.run"
  _make_self_extract "$bundle_dir" "$outbase"

  ok "Offline bundle created: ${outbase}"
  echo
  echo -e "${BOLD}${WHT}Remote one-liner${RST}"
  hr
  echo "1) Copy this file to OUT server (FTP/SCP/USB):"
  echo "   ${outbase}"
  echo
  echo "2) On OUT server run (one line):"
  echo "   sudo bash ./$(basename "$outbase")"
  echo
  echo -e "${DIM}Tip:${RST} After running, check: systemctl status wg-quick@${WG_IF} mimic@<wan_if>"
  echo
  pause
}
