# shellcheck shell=bash
# Part of AZHDAR (modular)

wg_account_extract_field(){
  local key="$1"
  printf "%s\n" "${WG_ACCOUNT_CONFIG:-}" | sed -n "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*//p" | head -n1
}

wg_account_extract_meta(){
  local key="$1"
  printf "%s\n" "${WG_ACCOUNT_CONFIG:-}" | sed -n "s/^[[:space:]]*#[[:space:]]*AZHDAR_${key}[[:space:]]*=[[:space:]]*//p" | head -n1
}

wg_account_apply_runtime_vars(){
  [[ "${WG_MODE:-classic}" == "account" ]] || return 0
  local addr endpoint allowed keepalive dst_ip dst_port fwd_tcp fwd_udp
  addr="$(wg_account_extract_field Address)"
  endpoint="$(wg_account_extract_field Endpoint)"
  allowed="$(wg_account_extract_field AllowedIPs)"
  keepalive="$(wg_account_extract_field PersistentKeepalive)"
  dst_ip="$(wg_account_extract_meta FORWARD_DST_IP)"
  dst_port="$(wg_account_extract_meta DST_PORT)"
  fwd_tcp="$(wg_account_extract_meta FORWARD_TCP_PORTS)"
  fwd_udp="$(wg_account_extract_meta FORWARD_UDP_PORTS)"
  WG_ACCOUNT_ENDPOINT="${endpoint:-${WG_ACCOUNT_ENDPOINT:-}}"
  WG_ACCOUNT_ALLOWEDIPS="${allowed:-${WG_ACCOUNT_ALLOWEDIPS:-}}"
  [[ -n "$keepalive" ]] && KEEPALIVE="$keepalive"
  [[ -n "$dst_ip" ]] && FORWARD_DST_IP="$dst_ip"
  [[ -n "$dst_port" ]] && VLESS_DST_PORT="$dst_port"
  [[ -n "$fwd_tcp" ]] && FORWARD_TCP_PORTS="$fwd_tcp"
  [[ -n "$fwd_udp" ]] && FORWARD_UDP_PORTS="$fwd_udp"
  if [[ -n "$endpoint" ]]; then
    WG_PORT="${endpoint##*:}"
    [[ "$WG_PORT" == "$endpoint" ]] && WG_PORT="${WG_PORT:-443}"
    OUT_PUBLIC_IP="${endpoint%:*}"
    OUT_PUBLIC_IP="${OUT_PUBLIC_IP#[}"; OUT_PUBLIC_IP="${OUT_PUBLIC_IP%]}"
  fi
  if [[ -n "$addr" ]]; then
    local first4 first6
    first4="$(printf "%s" "$addr" | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep -m1 '/')"
    first4="$(printf "%s\n" "$addr" | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep -m1 -E '^[0-9.]+/[0-9]+$' || true)"
    first6="$(printf "%s\n" "$addr" | tr ',' '\n' | sed 's/^ *//;s/ *$//' | grep -m1 ':' || true)"
    if [[ -n "$first4" ]]; then
      ENABLE_TUN_IPV4="1"
      IR_WG_IP="${first4%/*}"
      TUN_SUBNET="$first4"
      OUT_WG_IP="peer"
    else
      ENABLE_TUN_IPV4="0"
      IR_WG_IP=""
      TUN_SUBNET=""
      OUT_WG_IP=""
    fi
    if [[ -n "$first6" ]]; then
      ENABLE_TUN_IPV6="1"
      IR_WG_IP6="${first6%/*}"
      TUN_SUBNET6="$first6"
      OUT_WG_IP6="peer"
    else
      ENABLE_TUN_IPV6="0"
      IR_WG_IP6=""
      TUN_SUBNET6=""
      OUT_WG_IP6=""
    fi
  fi
}

# -------------------- WireGuard configs (local/remote) --------------------
backup_file(){
  local f="$1"
  [[ -f "$f" ]] || return 0
  cp -a "$f" "${f}.bak.$(date +%s)" 2>/dev/null || true
}

write_wg_conf_local(){
  step "Write WireGuard config (local)"
  local cfg="/etc/wireguard/${WG_IF}.conf"
  backup_file "$cfg"
  local keyfile="/etc/wireguard/${WG_IF}.key"
  [[ -s "$keyfile" ]] || { err "Local WireGuard key is missing: $keyfile"; return 1; }
  local priv; priv="$(cat "$keyfile" 2>/dev/null || true)"
  [[ -n "$priv" ]] || { err "Local WireGuard private key is empty: $keyfile"; return 1; }
  [[ -n "${OUT_PUBKEY:-}" ]] || { err "OUT_PUBKEY is empty; remote key/config is not ready. Run wizard or Repair tunnel."; return 1; }

  local addr=""
  local allowed=""
  if [[ "${ENABLE_TUN_IPV4:-1}" == "1" && -n "${IR_WG_IP:-}" && -n "${TUN_SUBNET:-}" ]]; then
    local prefix4="${TUN_SUBNET##*/}"
    addr="${IR_WG_IP}/${prefix4}"
    allowed="${OUT_WG_IP}/32"
  fi
  if [[ "${ENABLE_TUN_IPV6:-0}" == "1" && -n "${IR_WG_IP6:-}" && -n "${TUN_SUBNET6:-}" ]]; then
    local prefix6="${TUN_SUBNET6##*/}"
    [[ -n "$addr" ]] && addr+=", "
    addr+="${IR_WG_IP6}/${prefix6}"
    [[ -n "$allowed" ]] && allowed+=", "
    allowed+="${OUT_WG_IP6}/128"
  fi
  [[ -n "$addr" && -n "$allowed" ]] || { err "No tunnel address families enabled. Enable IPv4 and/or IPv6."; return 1; }

  local endpoint; endpoint="$(format_ipport "${OUT_PUBLIC_IP}" "${WG_PORT}")"
  cat >"$cfg" <<EOF
# Generated by m0000hamad - WireGuard (IR) with Mimic
[Interface]
PrivateKey = ${priv}
Address = ${addr}
ListenPort = ${WG_PORT}
MTU = ${MTU}

[Peer]
PublicKey = ${OUT_PUBKEY}
EOF
  if [[ "${USE_PSK}" == "1" && -n "${PSK_VALUE:-}" ]]; then
    echo "PresharedKey = ${PSK_VALUE}" >>"$cfg"
  fi
  cat >>"$cfg" <<EOF
Endpoint = ${endpoint}
AllowedIPs = ${allowed}
PersistentKeepalive = ${KEEPALIVE}
EOF
  chmod 600 "$cfg"
  ok "Local WG config written: ${cfg}"
}


write_wg_conf_remote(){
  if [[ "${WG_MODE:-classic}" == "account" ]]; then
    ok "Remote WG config skipped (account mode)."
    return 0
  fi
  step "Write WireGuard config (remote)"
  local addr=""
  local allowed=""
  if [[ "${ENABLE_TUN_IPV4:-1}" == "1" && -n "${OUT_WG_IP:-}" && -n "${TUN_SUBNET:-}" ]]; then
    local prefix4="${TUN_SUBNET##*/}"
    addr="${OUT_WG_IP}/${prefix4}"
    allowed="${IR_WG_IP}/32"
  fi
  if [[ "${ENABLE_TUN_IPV6:-0}" == "1" && -n "${TUN_SUBNET6:-}" && -n "${OUT_WG_IP6:-}" && -n "${IR_WG_IP6:-}" ]]; then
    local prefix6="${TUN_SUBNET6##*/}"
    [[ -n "$addr" ]] && addr+=", "
    addr+="${OUT_WG_IP6}/${prefix6}"
    [[ -n "$allowed" ]] && allowed+=", "
    allowed+="${IR_WG_IP6}/128"
  fi
  [[ -n "$addr" && -n "$allowed" ]] || { err "No tunnel address families enabled. Enable IPv4 and/or IPv6."; return 1; }
  [[ -n "${IR_PUBKEY:-}" ]] || { err "IR_PUBKEY is empty; local key/config is not ready."; return 1; }

  if ! ssh_run_stdin_env_root     "WG_IF=${WG_IF}"     "ADDR=${addr}"     "WG_PORT=${WG_PORT}"     "MTU=${MTU}"     "IR_PUBKEY=${IR_PUBKEY}"     "USE_PSK=${USE_PSK:-0}"     "PSK_VALUE=${PSK_VALUE:-}"     "ALLOWED=${allowed}" <<'REMOTE'
set -euo pipefail
mkdir -p /etc/wireguard
umask 077
cfg="/etc/wireguard/${WG_IF}.conf"
if [ -f "$cfg" ]; then cp -a "$cfg" "$cfg.bak.$(date +%s)" || true; fi

keyfile="/etc/wireguard/${WG_IF}.key"
if [ ! -f "$keyfile" ]; then
  wg genkey > "$keyfile"
  chmod 600 "$keyfile"
fi
priv="$(cat "$keyfile")"

cat >"$cfg" <<EOF
# Generated by m0000hamad - WireGuard (OUT) with Mimic
[Interface]
PrivateKey = ${priv}
Address = ${ADDR}
ListenPort = ${WG_PORT}
MTU = ${MTU}

[Peer]
PublicKey = ${IR_PUBKEY}
EOF

if [[ "${USE_PSK}" == "1" && -n "${PSK_VALUE:-}" ]]; then
  echo "PresharedKey = ${PSK_VALUE}" >>"$cfg"
fi

cat >>"$cfg" <<EOF
AllowedIPs = ${ALLOWED}
EOF

chmod 600 "$cfg"
REMOTE
  then
    err "Remote WG config write failed."
    return 1
  fi
  ok "Remote WG config written."
}


